- docs/contributors.md
- docs/index.md
The links now get underlined when hovered and I fixed a HTML error in contributors.md. There was a &lt;/p&gt; without &lt;p&gt;
> Make the text in contributors.md white so it matches the theme better.

- docs/samples/midi-io.md
- mkdocs.yml
This is the documentation for Pull request [#114](https://github.com/codeoverflow-org/nodecg-io/pull/114) from nodecg-io. I documented a sample showing how you could use midi-input and midi-output in one bundle.
> Documented midi-io sample

- docs/contribute/create_sample.md
- docs/contribute/create_service.md
Docs update for https://github.com/codeoverflow-org/nodecg-io/pull/115
> Use typescript build mode for incremental compilation

- docs/samples/sacn-sender.md
Documented the sacn-sender sample from pr [126](https://github.com/codeoverflow-org/nodecg-io/pull/126) from nodecg-io
> Documented sacn-sender sample

- docs/samples/discord.md
The discord sample description was incorrect because the sample listens on the exact `ping` or `!ping` message and only replies with `pong` and doesn't ping back anything that is followed by the `!ping` message.
> Fix discord sample description

- docs/dependencies.md
- docs/index.md
- docs/samples/reddit.md
- docs/services.md
- mkdocs.yml
Do not merge until [#137](https://github.com/codeoverflow-org/nodecg-io/pull/137) is merged.
> Add reddit service docs

- docs/getting_started/install.md
I specifed the NodeCG version because NodeCG will crash if it's version is 1.3.x or higher. 
UNCAUGHT EXCEPTION! NodeCG will now exit.
Error: configuration param 'bundles.paths' not declared in the schema
at Object.validate (/home/user/workspace/nodecg/node_modules/convict/lib/convict.js:648:17)
at module.exports (/home/user/workspace/nodecg/lib/config/loader.js:266:16)
at Object.<anonymous> (/home/user/workspace/nodecg/lib/config/index.js:19:18)
at Module._compile (internal/modules/cjs/loader.js:1063:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
at Module.load (internal/modules/cjs/loader.js:928:32)
at Function.Module._load (internal/modules/cjs/loader.js:769:14)
at Module.require (internal/modules/cjs/loader.js:952:19)
at require …
> Specified NodeCG version

- docs/samples/irc.md
For https://github.com/codeoverflow-org/nodecg-io/pull/215
> Add IRC sample documentation

- docs/getting_started/install.md
Updates the installation guide to use the nodecg-io [cli](https://github.com/codeoverflow-org/nodecg-io-cli) as discussed in https://github.com/codeoverflow-org/nodecg-io/issues/227
> Update install guide to use nodecg-io cli

- docs/getting_started/create_bundle.md
Updates the "create your first bundle" guide to use the `nodecg-io generate` command, which can automatically generate a bundle with a stub implementation.
> Update create a bundle guide to generate bundles using cli

- docs/contribute/contribute.md
- docs/getting_started/configuration.md
- docs/stylesheets/colors.css
- mkdocs.yml
Explains how automatic login (https://github.com/codeoverflow-org/nodecg-io/pull/241) can be configured.
Also reformats `docs/stylesheets/colors.css`. This was done automatically by prettier from the code repository
> Add documentation for automatic login

- docs/index.md
- docs/samples/sql.md
- mkdocs.yml
Adds docs for https://github.com/codeoverflow-org/nodecg-io/pull/237.
> Add sample doc for SQL service

- docs/samples/nanoleaf.md
- mkdocs.yml
Adds sample documentation for nanoleaf service (https://github.com/codeoverflow-org/nodecg-io/pull/180)
> Add sample doc entry for nanoleaf service

- docs/index.md
- docs/samples/atem.md
- docs/services.md
- mkdocs.yml
Merge with https://github.com/codeoverflow-org/nodecg-io/pull/286
> Add documentation for Atem Service

- .github/workflows/deploy.yaml
- docs/contribute/contribute.md
- docs/contribute/create_service.md
- docs/index.md
- mkdocs.yml
Updates references to `master` to `main` in the documentation and in the GitHub Action publis .workflow
Check https://github.com/codeoverflow-org/nodecg-io/issues/266 for more details.
> Update docs and Action workflows for master to main renaming

- .github/dependabot.yml
Saturday is update day ;)
Should reduce spam a bit by compressing multiple updates per week into one single PR.
> Only run dependabot update check once peer week

- .github/workflows/deploy.yaml
We're having the same problem here as in the main repository.
Commits caused by dependabot updates only have a read access token because of which the push to the `gh-pages` branch failes. To fix this we're doing the same, which is to ignore dependabot commits and run the workflow using a cronjob to still update the changes from dependabot in a timely manner.
> Don't try to publish docs on a dependabot commit

- docs/getting_started/existing_bundle.md
- mkdocs.yml
mkdocs-material has a new alternative implementation for tabs since
version [7.3.1](https://github.com/squidfunk/mkdocs-material/releases/tag/7.3.1). This PR enables it because it is nice IMHO.
Also removes tabs where language is not important and applies to both
TypeScript and JavaScript in the migration guide.
> Use alternative tabbed view and rework migration guide code tabs

- docs/getting_started/use_replicants.md
- mkdocs.yml
Adds documentation on the usage of service replicants like the streamelements replicant that is added in https://github.com/codeoverflow-org/nodecg-io/pull/494.
> Add documentation for streamelements replicant

- docs/getting_started/install.md
See https://github.com/codeoverflow-org/nodecg-io-cli/commit/ff8808a742e4936fe6f4974c151c12b9aa1d6f80.
Since some of our dependencies (like husky) require node.js 14, we need to bump our minimum required node.js version from 12 to 14.
> Bump minimum supported node.js version from 12 to 14.14.0

- package.json
NodeCG tries to load the docs repository as a bundle when it is cloned inside the nodecg-io repository as that root path is set as a bundle directory. Because of this we need (and always needed) this stub package.json so NodeCG thinks its a empty bundle and does not crash on startup.
Now that NodeCG v2 is released an error is shown at startup because NodeCG v2 is not included in the range of compatible NodeCG version. This PR updates the range to include any version of NodeCG because nothing is loaded here anyway.
> Update stub package.json to not error with NodeCG v2

- docs/getting_started/security_considerations.md
- docs/getting_started/use_replicants.md
- mkdocs.yml
Adds a documentation entry about our security considerations and tells users what and what not to expect from nodecg-io regarding handling of the entered configuration and credentials.
For https://github.com/codeoverflow-org/nodecg-io/pull/424
> Add doc entry about security considerations of nodecg-io

- .gitignore
- docs/samples/gametts.md
- mkdocs.yml
Related pull request: https://github.com/codeoverflow-org/nodecg-io/pull/991
> feat(gametts): Add gametts service
