- docs/contribute/create_service.md
https://github.com/codeoverflow-org/nodecg-io/pull/43
> Changes due to PR # 43

- docs/samples/streamdeck.md
- mkdocs.yml
Do not merge until [#36](https://github.com/codeoverflow-org/nodecg-io/pull/36) is merged.
> Added documentation for #36

- docs/samples/xdotool.md
- mkdocs.yml
Do not merge until [#60](https://github.com/codeoverflow-org/nodecg-io/pull/60) is merged.
> Added xdotool sample documentation

- docs/stylesheets/colors.css
changed the checked checkbox color to primary
> adjusted checkbox color to primary

- docs/samples/telegram.md
https://github.com/codeoverflow-org/nodecg-io/pull/69
> Added Telegram documentation

- docs/samples/slack.md
- docs/services.md
Only Merge wenn [#70 of code overflow-org/nodecg-io is merged](https://github.com/codeoverflow-org/nodecg-io/pull/70)
> Added Slack Service Docs

- docs/samples/youtube.md
Added documentation for the YouTube sample bundle.
> Added youtube sample doc

- docs/contribute/contribute.md
- docs/getting_started/install.md
Doc update for https://github.com/codeoverflow-org/nodecg-io/pull/74
> Move bootstrapping using lerna into its own npm script

- docs/contribute/create_sample.md
- docs/contribute/create_service.md
- docs/getting_started/create_bundle.md
Documents changes from https://github.com/codeoverflow-org/nodecg-io/pull/80 and also includes some other fixes.
> Reduce boilerplate for bundles using services

- docs/contribute/create_service.md
Doc update for https://github.com/codeoverflow-org/nodecg-io/pull/68
> Update create service doc with changes of the common service interface

- docs/contribute/contribute.md
- docs/getting_started/install.md
https://discordapp.com/channels/577412066994946060/577495219399032864/754644742796476525
> Update install guide to include native requirements for node-gyp

- docs/samples/midi-input.md
- mkdocs.yml
Documented the midi input sample similarly like the twitch chat one.
> documented midi input sample

- docs/samples/ws-client.md
Documented the sample for the websocket client with the current pull-request [nodecg-io#119](https://github.com/codeoverflow-org/nodecg-io/pull/119).
> Documented the websocket-client sample

- docs/samples/rcon.md
whoops, forgot to to a Pull request.
> Create rcon sample documentation.

- docs/contribute/create_sample.md
- docs/contribute/create_service.md
Reflects package.json updates from https://github.com/codeoverflow-org/nodecg-io/pull/131
> Update package.json templates

- docs/samples/spotify.md
- mkdocs.yml
Sample PR: https://github.com/codeoverflow-org/nodecg-io/pull/148
> Add doc for spotify sample

- docs/samples/twitch-chat.md
- mkdocs.yml
See https://github.com/codeoverflow-org/nodecg-io/pull/151
> Rename twitch service to twitch-chat

- docs/samples/streamelements.md
- mkdocs.yml
Adds streamelements sample doc for https://github.com/codeoverflow-org/nodecg-io/issues/150.
> Add sample doc for streamelements-events sample

- docs/samples/obs.md
- mkdocs.yml
Adds obs sample doc for codeoverflow-org/nodecg-io#150.
> Add sample doc for obs-scenelist sample

- docs/contribute/create_sample.md
- docs/contribute/create_service.md
Documentation update for https://github.com/codeoverflow-org/nodecg-io/pull/163
> Use easier way of importing core

- docs/index.md
- docs/samples/twitch-api.md
- mkdocs.yml
Sample for https://github.com/codeoverflow-org/nodecg-io/pull/169
> Add twitch-api sample documenation

- docs/samples/twitch-pubsub.md
- mkdocs.yml
Adds doc needed by https://github.com/codeoverflow-org/nodecg-io/issues/150
> Add twitch pubsub sample documentation

- docs/samples/philipshue.md
- mkdocs.yml
Adds philips hue docs for https://github.com/codeoverflow-org/nodecg-io/issues/150.
Also finally closes https://github.com/codeoverflow-org/nodecg-io/issues/150
> Add Philips Hue sample doc

- docs/dependencies.md
- docs/index.md
- docs/samples/twitch-addons.md
- docs/services.md
- mkdocs.yml
Do not merge until https://github.com/codeoverflow-org/nodecg-io/pull/199 is merged.
> Documentation for #199

- docs/samples/debug.md
For https://github.com/codeoverflow-org/nodecg-io/pull/205
> Add sample doc for debug service

- docs/getting_started/create_new_bundle.md
For https://github.com/codeoverflow-org/nodecg-io-cli/pull/62 / https://github.com/codeoverflow-org/nodecg-io/issues/336
> Add support for generating bundles using the cli with dev installs

- docs/samples/spotify.md
The links to the spotify guides have changed. 
This PR updates these two links.
> Update spotify links.

- docs/samples/artnet.md
Improving the note about timings which are needed to be implemented. The current text appeared unclear.
> Rewrite part of the ArtNet documentation
